require:
  - rubocop-performance

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Style/SymbolProc:
  Enabled: false
