inherit_gem:
  theforeman-rubocop:
    - strictest.yml

AllCops:
  TargetRubyVersion: 2.7

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
